version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: myes
    environment:
      discovery.type: single-node
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200" #暴露给用户
      - "9300:9300" #组件之间互联
    networks:
      - esNet
  kibana:
    image: kibana:7.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://myes:9200
    ports:
      - "5601:5601"
    networks:
      - esNet
networks:
  esNet: { }
