version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: es
    environment:
      discovery.type: single-node
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200" #暴露给用户
      - "9300:9300" #组件之间互联
    networks:
      - esNet
  kibana:
    image: kibana:8.7.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    networks:
      - esNet
networks:
  esNet: { }
