version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: sp-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my_root
      - MYSQL_DATABASE=file
      - MYSQL_USER=file
      - MYSQL_PASSWORD=file
      - MYSQL_USER2=canal
      - MYSQL_PASSWORD2=canal
    ports:
      - "3317:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./conf/my.cnf:/etc/my.cnf
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: sp-es
    environment:
      discovery.type: single-node
    volumes:
      - ./myes/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200" #暴露给用户
      - "9300:9300" #组件之间互联
    networks:
      - esNet
  kibana:
    image: kibana:7.12.1
    container_name: sp-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - esNet
networks:
  esNet: { }
